configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/evrim%2Fcartography-83beb71baf389d72fee2e6d0cc1b3bebe873cf055630da35fe8d7b57f822115d.yml
openapi_spec_hash: a33e786e3c3e6cd1afeddfc718827bcf
config_hash: 68aa5cb29628bd3fdd0fe5588a71fe2c
